apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kuard
    internalVersion: "0.0.2"  # Çift tırnak içinde bir sürüm numarası
  name: kuard
spec:
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:1
    imagePullPolicy: IfNotPresent
    name: kuard
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never  # Yeni satır eklenmiş ve düzeltilmiş indentasyon
